[tool.bumpversion]
commit = true
current_version = "11.4.0"
message = 'Geant4 {new_version}'
tag = true
tag_name = "geant4-{new_version}"
tag_message = "Geant4 {new_version} binaries for Calzone."

[[tool.bumpversion.files]]
filename = ".github/workflows/build-geant4.yml"
search = '''
env:
  GEANT4_VERSION: '{current_version}'
'''
replace = '''
env:
  GEANT4_VERSION: '{new_version}'
'''
